// Generated by https://quicktype.io

export interface GetOwnProfileType {
  message: string;
  data: Data;
  statusCode: number;
}

export interface Data {
  email: string;
  name: string;
  password: string;
  roles: string[];
  id: number;
  avatar_link: string;
}
